services:
  postgres:
    image: postgres
    container_name: postgres_crud
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/db/
    volumes:
      - ./back/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_conf/nginx-conf.d:/etc/nginx/conf.d/default.conf
      - ./front:/usr/share/nginx/html
    ports:
    - "80:80"

  express:
    container_name: express
    build:
      context: back/
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./back/data:/data





